# Generated by Django 2.1.7 on 2019-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190430_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='seo_descr',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/products/%Y%/%m/%d/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_descr',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='seo_descr',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
    ]
